version: '3.4'

services:
  web:
    image: heinrichad/dyndns-web
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - app-data:/usr/src:ro

  app:
    image: heinrichad/dyndns-app
    volumes:
      - app-data:/usr/src:rw

volumes:
  app-data:
    driver: local